export const EMAIL_LIST_FETCH_START = 'EMAIL_LIST_FETCH_START'
export const EMAIL_LIST_FETCH_SUCCESS = 'EMAIL_LIST_FETCH_SUCCESS'
export const EMAIL_LIST_FETCH_ERROR = 'EMAIL_LIST_FETCH_ERROR'

export const EMAIL_LIST_PAGESIZE_CHANGE = 'EMAIL_LIST_PAGESIZE_CHANGE'

export const EMAIL_LIST_ROW_CLICK = 'EMAIL_LIST_ROW_CLICK'